allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - "@astrojs/internal-helpers@0.12.0"
  - "@astrojs/markdown-satteri@0.4.3"
  - astro@7.3.6
  - fast-uri@3.1.6 || 3.1.7 || 3.1.8
  - js-yaml@4.3.2
  - http-cache-semantics@4.2.1
  - smol-toml@1.8.1
  - source-map-js@1.2.2
  - postcss-selector-parser@7.1.6
  - sharp@0.35.5
